//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samplewebapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public string FullName { get; set; }
        public long MobileNumber { get; set; }
        public Nullable<long> PinCode { get; set; }
        public string FlatNO { get; set; }
        public string BuildingName { get; set; }
        public string Street { get; set; }
        public string Village { get; set; }
        public string City { get; set; }
        public string states { get; set; }
    }
}
