//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samplewebapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string prodId { get; set; }
        public string prodName { get; set; }
        public string prodimage { get; set; }
        public string prodDescription { get; set; }
        public Nullable<decimal> prodprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> total { get; set; }
    }
}
