//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samplewebapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pproject
    {
        public string startDate { get; set; }
        public string TeamLeader { get; set; }
        public string projectName { get; set; }
        public Nullable<int> Teamsize { get; set; }
    }
}
