//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samplewebapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string ContactNO { get; set; }
        public string Address { get; set; }
        public Nullable<int> PANNo { get; set; }
        public Nullable<int> BankIFCSCode { get; set; }
        public int BankAccountNo { get; set; }
    }
}
