//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace samplewebapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentTable
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int rollno { get; set; }
        public string branch { get; set; }
        public Nullable<int> marks { get; set; }
    }
}
